# Generated by Django 2.1.4 on 2019-01-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FOAAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_1', models.TextField()),
                ('box_2', models.TextField()),
                ('box_3', models.TextField()),
                ('box_4', models.TextField()),
                ('message_url', models.URLField()),
            ],
        ),
    ]
