# Generated by Django 2.1.4 on 2019-01-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foaas',
            name='box_4',
        ),
    ]
