# Generated by Django 2.1.4 on 2019-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_foaas_box_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('fields', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
