# Generated by Django 2.1.4 on 2019-01-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_apiendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='foaas',
            name='foaas_message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
