# Generated by Django 2.1.4 on 2019-01-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190105_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foaas',
            name='box_1',
            field=models.TextField(blank=True),
        ),
    ]
