# Generated by Django 2.1.4 on 2019-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20190106_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='foaas',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
